#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-joda-convert
Version  : 1.7
Release  : 1
URL      : https://github.com/JodaOrg/joda-convert/archive/v1.7.tar.gz
Source0  : https://github.com/JodaOrg/joda-convert/archive/v1.7.tar.gz
Source1  : https://repo1.maven.org/maven2/org/joda/joda-convert/1.7/joda-convert-1.7.jar
Source2  : https://repo1.maven.org/maven2/org/joda/joda-convert/1.7/joda-convert-1.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-joda-convert-data = %{version}-%{release}
Requires: mvn-joda-convert-license = %{version}-%{release}

%description
Joda-Convert
------------
Joda-Convert provides a small set of classes to aid conversion between Objects and Strings.
It is not intended to tackle the wider problem of Object to Object transformation.

%package data
Summary: data components for the mvn-joda-convert package.
Group: Data

%description data
data components for the mvn-joda-convert package.


%package license
Summary: license components for the mvn-joda-convert package.
Group: Default

%description license
license components for the mvn-joda-convert package.


%prep
%setup -q -n joda-convert-1.7

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-joda-convert
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-joda-convert/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/joda/joda-convert/1.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/joda/joda-convert/1.7/joda-convert-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/joda/joda-convert/1.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/joda/joda-convert/1.7/joda-convert-1.7.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/joda/joda-convert/1.7/joda-convert-1.7.jar
/usr/share/java/.m2/repository/org/joda/joda-convert/1.7/joda-convert-1.7.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-joda-convert/LICENSE.txt
